import type { ReactNode } from 'react'
import {
  AWSIcon,
  CloudflareIcon,
  CypressIcon,
  DockerIcon,
  FastifyIcon,
  FlaskIcon,
  GiteaIcon,
  GithubActionsIcon,
  GithubIcon,
  GitIcon,
  GoIcon,
  JavascriptIcon,
  LinkedinIcon,
  NextIcon,
  NodeJSIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  TailwindIcon,
  TraefikIcon,
  TypescriptIcon,
  ViteIcon,
  WhatsappIcon,
  ZodIcon,
} from '.'

export const iconsNode: Record<string, ReactNode> = {
  aws: <AWSIcon className="transition hover:scale-125" />,
  cloudflare: <CloudflareIcon className="transition hover:scale-125" />,
  cypress: <CypressIcon className="transition hover:scale-125" />,
  docker: <DockerIcon className="transition hover:scale-125" />,
  fastify: <FastifyIcon className="transition hover:scale-125" />,
  flask: <FlaskIcon className="transition hover:scale-125" />,
  git: <GitIcon className="transition hover:scale-125" />,
  gitea: <GiteaIcon className="transition hover:scale-125" />,
  githubactions: <GithubActionsIcon className="transition hover:scale-125" />,
  github: <GithubIcon className="transition hover:scale-125" />,
  golang: <GoIcon className="transition hover:scale-125" />,
  javascript: <JavascriptIcon className="transition hover:scale-125" />,
  linkedin: <LinkedinIcon className="transition hover:scale-125" />,
  next: <NextIcon className="transition hover:scale-125" />,
  nodejs: <NodeJSIcon className="transition hover:scale-125" />,
  prisma: <PrismaIcon className="transition hover:scale-125" />,
  python: <PythonIcon className="transition hover:scale-125" />,
  react: <ReactIcon className="transition hover:scale-125" />,
  tailwind: <TailwindIcon className="transition hover:scale-125" />,
  traefik: <TraefikIcon className="transition hover:scale-125" />,
  typescript: <TypescriptIcon className="transition hover:scale-125" />,
  vite: <ViteIcon className="transition hover:scale-125" />,
  whatsapp: <WhatsappIcon className="transition hover:scale-125" />,
  zod: <ZodIcon className="transition hover:scale-125" />,
}
