import { Layers } from 'lucide-react'
import {
  AWSIcon,
  BootstrapIcon,
  CSSIcon,
  CloudflareIcon,
  CypressIcon,
  DockerIcon,
  DrizzleIcon,
  ExpoIcon,
  FastifyIcon,
  FigmaIcon,
  FlaskIcon,
  FlutterIcon,
  GitHubIcon,
  GitIcon,
  GiteaIcon,
  GithubActionsIcon,
  GoIcon,
  HTMLIcon,
  JavascriptIcon,
  JestIcon,
  LinkedInIcon,
  NestJSIcon,
  NextIcon,
  NodeJSIcon,
  PostgreSQLIcon,
  PrismaIcon,
  PythonIcon,
  RadixUIIcon,
  ReactHookFormIcon,
  ReactIcon,
  ReactQueryIcon,
  RedisIcon,
  ShadcnuiIcon,
  TailwindIcon,
  TraefikIcon,
  TypescriptIcon,
  ViteIcon,
  WhatsAppIcon,
  ZodIcon,
} from '.'
import { ReactNativeIcon } from './react-native'

export const iconsNode: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  aws: AWSIcon,
  bootstrap: BootstrapIcon,
  cloudflare: CloudflareIcon,
  css: CSSIcon,
  cypress: CypressIcon,
  drizzle: DrizzleIcon,
  expo: ExpoIcon,
  html: HTMLIcon,
  jest: JestIcon,
  nestjs: NestJSIcon,
  postgresql: PostgreSQLIcon,
  radixui: RadixUIIcon,
  reacthookform: ReactHookFormIcon,
  redis: RedisIcon,
  tanstackquery: ReactQueryIcon,
  shadcnui: ShadcnuiIcon,
  docker: DockerIcon,
  fastify: FastifyIcon,
  figma: FigmaIcon,
  flask: FlaskIcon,
  flutter: FlutterIcon,
  fullstack: Layers,
  git: GitIcon,
  gitea: GiteaIcon,
  githubactions: GithubActionsIcon,
  github: GitHubIcon,
  golang: GoIcon,
  javascript: JavascriptIcon,
  linkedin: LinkedInIcon,
  nextjs: NextIcon,
  nodejs: NodeJSIcon,
  prisma: PrismaIcon,
  python: PythonIcon,
  react: ReactIcon,
  reactnative: ReactNativeIcon,
  tailwind: TailwindIcon,
  traefik: TraefikIcon,
  typescript: TypescriptIcon,
  vite: ViteIcon,
  whatsapp: WhatsAppIcon,
  zod: ZodIcon,
}
