import type { ReactNode } from 'react'
import {
  AWSIcon,
  CloudflareIcon,
  CypressIcon,
  DockerIcon,
  FastifyIcon,
  FlaskIcon,
  GiteaIcon,
  GithubActionsIcon,
  GithubIcon,
  GitIcon,
  GoIcon,
  JavascriptIcon,
  LinkedinIcon,
  NextIcon,
  NodeJSIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  TailwindIcon,
  TraefikIcon,
  TypescriptIcon,
  ViteIcon,
  WhatsappIcon,
  ZodIcon,
} from '.'

export const iconsNode: Record<string, ReactNode> = {
  aws: <AWSIcon />,
  cloudflare: <CloudflareIcon />,
  cypress: <CypressIcon />,
  docker: <DockerIcon />,
  fastify: <FastifyIcon />,
  flask: <FlaskIcon />,
  git: <GitIcon />,
  gitea: <GiteaIcon />,
  githubactions: <GithubActionsIcon />,
  github: <GithubIcon />,
  golang: <GoIcon />,
  javascript: <JavascriptIcon />,
  linkedin: <LinkedinIcon />,
  next: <NextIcon />,
  nodejs: <NodeJSIcon />,
  prisma: <PrismaIcon />,
  python: <PythonIcon />,
  react: <ReactIcon />,
  tailwind: <TailwindIcon />,
  traefik: <TraefikIcon />,
  typescript: <TypescriptIcon />,
  vite: <ViteIcon />,
  whatsapp: <WhatsappIcon />,
  zod: <ZodIcon />,
}
